[package]
name = "rupl"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "a complex graphing library"
authors = ["bgkillas <mswalhelm@gmail.com>"]

[features]
default=["egui"]
egui=["dep:egui"]
skia=["dep:skia-safe","dep:softbuffer"]

[dependencies]
eyre = "0.6.12"
rayon = "1.10.0"
egui={version="0.31.1", optional=true}
skia-safe={version="0.84.0", optional=true}
softbuffer={version="0.4.6", optional=true}