[package]
name = "rupl"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "a complex graphing library"
authors = ["bgkillas <mswalhelm@gmail.com>"]

[dependencies]
egui="0.31.1"
eyre = "0.6.12"
rayon = "1.10.0"